### ISSUE TITLE
[Question] Hibernate L2 maximum size configuration

### ISSUE THREAD

**Issue by marceloverdijk** [ben-manes/caffeine#268]
I'm trying to use Caffeine as a Hibernate L2 cache provider.

The basic setup works with:

```
hibernate:
        cache:
          use_second_level_cache: true
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        javax.cache.provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
```

The caches created are Caffeine's `BoundedLocalCache` instances.

I'm now trying to set the maximum size of each Entity's cache (without success).

I tried adding an `application.conf` in my resources path containing:

```
caffeine.jcache {
  com.mycomp.Book {
    # key-type = java.lang.Object
    # value-type = java.lang.Object
    monitoring {
      statistics = true
    }
    policy {
      maximum {
        size = 50
      }
    }
  }
}

```

but is does not pick it up.

Am I missing a step or is the configuration invalid?
