### ISSUE TITLE
Weird problem with Enum value from cache not able to use in reflection setter

### ISSUE THREAD

**Issue by marceloverdijk** [ben-manes/caffeine#387]
Hi,

I'm seeing some strange behaviour using Caffeine JCache as Hibernate L2 cache implementation.
I have a Spring Boot application with the following configuration properties:

```
spring:
  jpa:
    properties:
      hibernate:
        cache:
          region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
          use_second_level_cache: true
        javax:
          cache:
            provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
```

This basically tells Hibernate to use a JCache L2 cache using Caffeine.

The issue I'm having is that when retrieving a cached entity with an enum Hibernate throws the following exception:

```
org.hibernate.PropertyAccessException: Could not set field value [VIP] value by reflection : [class com.mycomp.domain.Customer.type] setter of com.mycomp.domain.Customer.type

cause: java.lang.IllegalArgumentException: Can not set com.mycomp.domain.CustomerType field com.mycomp.domain.Customer.type to com.mycomp.domain.CustomerType
```

I did some debugging and the actual value from the Caffeine cache does include the value for the enum.
But when Hibernate tries to set it in the entity via Reflection for some reason it cannot set it.

I switched the provider from `com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider` to `org.ehcache.jsr107.EhcacheCachingProvider` to see if that worked and surprisingly it worked..

I wonder if you have heard about such an issue before... I'm not expecting it is a Caffeine issue (as I see that the actual cached value looks as expected) but I cannot explain why it is working with Ehcache... could it maybe be classloader issue or something?

**Comment by ben-manes** [comment]
That is strange. I haven't used Hibernate/JPA or Spring in many years (XML days), so I am familiar but very rusty.

I agree it does sound like a classloader issue. JCache does require Java serialization by default (`storeByValue` is true), which you should generally disable. That then requires that we copy the key/value between the caller and the cache, where we provide a `Copier` interface. I followed the [JCache RI](https://github.com/jsr107/RI) by passing through the CacheManager's ClassLoader.

Perhaps the classloader used by Hibernate to create the CacheManager differs from the runtime? Or perhaps Ehcache has a workaround to violate the spec and disabled copying by default? Can copying be disabled or does the session proxying require it? Also, how & what is your caffeine cache (e.g. by Java or by the Typesafe Config)?

**Comment by marceloverdijk** [comment]
The Caffeine caches are created "by" Hibernate (I'm not creating them manually). Hibernate calls the cache provider to create the cache when it does not exist.

I'm investigating now a bit further with class loader.

**Comment by ben-manes** [comment]
In that case, I'd expect it to be using `MutableConfiguration` where `isStoreByValue` is true by default, forcing the entries to be serialized. This of course also means that the cache is unbounded since JCache only supports expiration, not size eviction. The magic of silently creating unbounded caches is something I dislike about JCache and its integrations.

The Ehcache 2 team defined the JCache spec and wrote a non-production working RI. Later the Ehcache 3 team wrote Hibernate's JCache adapter, so perhaps they decided on a different default classloader based on real usage rather than the RI's guess.

I haven't looked at Hibernate + JCache for a while, but you might be interested in this [JIRA ticket](https://hibernate.atlassian.net/browse/HHH-11953) about the silent cache creation, concerns, etc.

**Comment by marceloverdijk** [comment]
Yes I think it is a class loader issue.

I changed my Sprint Boot setup so Spring Boot creates the JCache cache manager instead, and passes it to Hibernate. With that setup everything works as expected and I don't see the issue.

What I did:

```
spring:
  cache:
    type: jcache # Tells Spring Boot to use JCache and to use the Caffeine provider
    jcache.provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
```

Next to that I had to enable Spring caching with `@EnableCaching` ass pass the by Spring created `JCacheCacheManager` to Hibernate:

```
@Configuration
@EnableCaching
public class CacheConfig {

    @Bean
    public HibernatePropertiesCustomizer hibernatePropertiesCustomizer(JCacheCacheManager jCacheManager) {
        return (properties) -> properties.put(ConfigSettings.CACHE_MANAGER, jCacheManager.getCacheManager());
    }
}

```
 (maybe this could help somebody in the future)
